[pyprland]
plugins = [
  "scratchpads"
]
[scratchpads.music]
animation = "fromBottom"
command = "kitty --class kitty-pulsemixer -e pulsemixer"
class = "kitty-pulsemixer"
size = "50% 20%"
offset = "200%"
